server:
  port: ${PORT:8080}

spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    database: h2
  datasource:
    url: "jdbc:h2:mem:db;DB_CLOSE_DELAY=-1"
    username: "sa"
    password: "sa"
    driver-class-name: org.h2.Driver

marvel:
  api:
    url: https://gateway.marvel.com:443
    key:
      public: ${MARVEL_PUBLIC_KEY}
      private: ${MARVEL_PRIVATE_KEY}
    limit: 100


translate:
  api:
    url: https://api.mymemory.translated.net